### ISSUE TITLE
Support S3 API implementations such as RiakCS / Swift

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/postgresbackup-boshrelease#1]
Thanks for sharing this great release!

I'm running a private CF instance which has not access to AWS S3, but local implementation of the S3 API: swift or RiakCS. It could be great if the base URL could be configureable to not always point on the default AWS S3 US enpoint, but potentially point on a private Swift/RiakCS endpoint.

gof3r seems to [support a `--endpoint` option](http://randallmcpherson.com/gof3r.html) which defaults to [s3.amazonaws.com](https://godoc.org/github.com/rlmcpherson/s3gof3r#S3)

I guess supporting dump into RiakCS it would only take to add the --endpoint to the gof3r binary into https://github.com/cloudfoundry-community/postgresbackup-boshrelease/blob/1dcb4e3f8da571c7b2b725e8ab89b20e585bafa1/jobs/pgbackup/templates/bin/pgbackup#L35 and add a new corresponding property pgbackup.s3.endpoint property to https://github.com/cloudfoundry-community/postgresbackup-boshrelease/blob/master/jobs/pgbackup/spec#L54-L65

Do you see other potential problems to be careful about ? If not, I might give it a try in coming weeks.

/CC @poblin-orange

**Comment by thegullion** [comment]
Guillaume, 

Check out v2 - added the --endpoint option and support for multiple postgres versions. 

Chris

**Comment by gberche-orange** [comment]
thanks a lot @thegullion! I'll be testing this shortly against riakcs.
