### ISSUE TITLE
S3_ENDPOINT: unbound variable

### ISSUE THREAD

**Issue by kkitai** [cloudfoundry-community/postgresbackup-boshrelease#6]
Hi

thanks for the useful release.
I'm gonna use this release in our company.

but, I take error message.

```
>> /var/vcap/packages/postgres95/bin/pg_dumpall -c --no-password  -> S3 concourse:/postgres-backup/2017/02/24/20170224095446-postgres-backup.gz
/var/vcap/jobs/pgbackup/bin/pgbackup: line 41: S3_ENDPOINT: unbound variable
FAILED to back up!
pgbackup shutting down
```

it looks like there are unnecessary space at here.

https://github.com/cloudfoundry-community/postgresbackup-boshrelease/blob/master/jobs/pgbackup/templates/bin/pgbackup#L50

**Comment by shinji62** [comment]
@kkitai Please make PR.

**Comment by jhunt** [comment]
I think this has been fixed in recent revisions: https://github.com/cloudfoundry-community/postgresbackup-boshrelease/blob/master/jobs/pgbackup/templates/bin/pgbackup#L67

**Comment by alexanelli** [comment]
@kkitai based on the revisions jhunt mentioned above, would you like me to close this issue?
